apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: audit-zone
spec:
  containers:
  - name: privileged-pod-nginx
    image: nginx:latest
    securityContext:
      privileged: true 
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
