apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
  namespace: audit-zone
spec:
  containers:
  - name: root-user-pod-nginx
    image: nginx:latest
    securityContext:
      runAsNonRoot: false
      readOnlyRootFilesystem: true
      runAsUser: 0
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
