apiVersion: v1
kind: Pod
metadata:
  name: secure-hostpath-pod
  namespace: audit-zone
spec:
  containers:
  - name: hosttpath-pod-nginx
    image: nginx:latest
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
    volumeMounts:
    - name: host-logs
      mountPath: /usr/share/nginx/html/logs
  volumes:
  - name: host-logs

