apiVersion: v1
kind: Pod
metadata:
  name: secure-root-user-pod
  namespace: audit-zone
spec:
  containers:
  - name: root-user-pod-nginx
    image: nginx:latest
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
